#ifndef POCKETOS_DRIVER_CONFIG_H
#define POCKETOS_DRIVER_CONFIG_H

/**
 * PocketOS Driver Configuration and Tiering System
 * 
 * This file defines the driver tiering system that allows compile-time
 * selection of driver feature sets to optimize for code size vs features.
 * 
 * Driver Tiers:
 * - Tier 0: Basic functionality only (minimum useful features)
 * - Tier 1: Robust features (calibration, configuration, extra outputs)
 * - Tier 2: Complete + exhaustive register access
 */

// ============================================================================
// GLOBAL DRIVER TIER CONFIGURATION
// ============================================================================

/**
 * POCKETOS_DRIVER_TIER: Global driver tier setting
 * 
 * 0 = TIER_0  - Basic functionality, minimum useful features
 * 1 = TIER_1  - Robust features with configuration (DEFAULT)
 * 2 = TIER_2  - Complete with exhaustive register access
 * 
 * Can be overridden via build flags: -DPOCKETOS_DRIVER_TIER=2
 */
#ifndef POCKETOS_DRIVER_TIER
#define POCKETOS_DRIVER_TIER 1  // Default to TIER_1
#endif

// Tier level definitions
#define POCKETOS_TIER_0  0
#define POCKETOS_TIER_1  1
#define POCKETOS_TIER_2  2

// Legacy compatibility: map old PACKAGE to new TIER
#ifdef POCKETOS_DRIVER_PACKAGE
#if POCKETOS_DRIVER_PACKAGE == 1
#undef POCKETOS_DRIVER_TIER
#define POCKETOS_DRIVER_TIER 0
#elif POCKETOS_DRIVER_PACKAGE == 2
#undef POCKETOS_DRIVER_TIER
#define POCKETOS_DRIVER_TIER 1
#elif POCKETOS_DRIVER_PACKAGE == 3
#undef POCKETOS_DRIVER_TIER
#define POCKETOS_DRIVER_TIER 2
#endif
#endif

// ============================================================================
// PER-DRIVER TIER OVERRIDES
// ============================================================================

/**
 * Per-driver tier overrides allow individual drivers to use a different
 * tier than the global package setting.
 * 
 * Example: Use full BME280 driver even in minimal package:
 *   -DPOCKETOS_DRIVER_TIER_BME280=3
 */

// BME280 Driver Tier (Temperature/Humidity/Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_BME280
#define POCKETOS_DRIVER_TIER_BME280 POCKETOS_DRIVER_TIER
#endif

// GPIO Digital Output Driver Tier
#ifndef POCKETOS_DRIVER_TIER_GPIO_DOUT
#define POCKETOS_DRIVER_TIER_GPIO_DOUT POCKETOS_DRIVER_TIER
#endif

// SHT31 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SHT31
#define POCKETOS_DRIVER_TIER_SHT31 POCKETOS_DRIVER_TIER
#endif

// AS6212 Driver Tier (Temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_AS6212
#define POCKETOS_DRIVER_TIER_AS6212 POCKETOS_DRIVER_TIER
#endif

// MCP9808 Driver Tier (Temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_MCP9808
#define POCKETOS_DRIVER_TIER_MCP9808 POCKETOS_DRIVER_TIER
#endif

// TMP102 Driver Tier (Temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_TMP102
#define POCKETOS_DRIVER_TIER_TMP102 POCKETOS_DRIVER_TIER
#endif

// TMP117 Driver Tier (Temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_TMP117
#define POCKETOS_DRIVER_TIER_TMP117 POCKETOS_DRIVER_TIER
#endif

// STTS751 Driver Tier (Temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_STTS751
#define POCKETOS_DRIVER_TIER_STTS751 POCKETOS_DRIVER_TIER
#endif

// MLX90614 Driver Tier (Infrared temperature sensor)
#ifndef POCKETOS_DRIVER_TIER_MLX90614
#define POCKETOS_DRIVER_TIER_MLX90614 POCKETOS_DRIVER_TIER
#endif

// AHT10 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_AHT10
#define POCKETOS_DRIVER_TIER_AHT10 POCKETOS_DRIVER_TIER
#endif

// AHT20 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_AHT20
#define POCKETOS_DRIVER_TIER_AHT20 POCKETOS_DRIVER_TIER
#endif

// AM2315 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_AM2315
#define POCKETOS_DRIVER_TIER_AM2315 POCKETOS_DRIVER_TIER
#endif

// SI7021 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SI7021
#define POCKETOS_DRIVER_TIER_SI7021 POCKETOS_DRIVER_TIER
#endif

// SHT35 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SHT35
#define POCKETOS_DRIVER_TIER_SHT35 POCKETOS_DRIVER_TIER
#endif

// SHT40 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SHT40
#define POCKETOS_DRIVER_TIER_SHT40 POCKETOS_DRIVER_TIER
#endif

// SHT45 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SHT45
#define POCKETOS_DRIVER_TIER_SHT45 POCKETOS_DRIVER_TIER
#endif

// SHTC3 Driver Tier (Temperature/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SHTC3
#define POCKETOS_DRIVER_TIER_SHTC3 POCKETOS_DRIVER_TIER
#endif

// BMP085 Driver Tier (Pressure sensor - legacy)
#ifndef POCKETOS_DRIVER_TIER_BMP085
#define POCKETOS_DRIVER_TIER_BMP085 POCKETOS_DRIVER_TIER
#endif

// BMP180 Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_BMP180
#define POCKETOS_DRIVER_TIER_BMP180 POCKETOS_DRIVER_TIER
#endif

// BMP280 Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_BMP280
#define POCKETOS_DRIVER_TIER_BMP280 POCKETOS_DRIVER_TIER
#endif

// BMP388 Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_BMP388
#define POCKETOS_DRIVER_TIER_BMP388 POCKETOS_DRIVER_TIER
#endif

// DPS310 Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_DPS310
#define POCKETOS_DRIVER_TIER_DPS310 POCKETOS_DRIVER_TIER
#endif

// MS5611 Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_MS5611
#define POCKETOS_DRIVER_TIER_MS5611 POCKETOS_DRIVER_TIER
#endif

// LPS22HB Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_LPS22HB
#define POCKETOS_DRIVER_TIER_LPS22HB POCKETOS_DRIVER_TIER
#endif

// LPS25H Driver Tier (Pressure sensor)
#ifndef POCKETOS_DRIVER_TIER_LPS25H
#define POCKETOS_DRIVER_TIER_LPS25H POCKETOS_DRIVER_TIER
#endif

// BME680 Driver Tier (Environmental multi-sensor)
#ifndef POCKETOS_DRIVER_TIER_BME680
#define POCKETOS_DRIVER_TIER_BME680 POCKETOS_DRIVER_TIER
#endif

// BME688 Driver Tier (Environmental multi-sensor)
#ifndef POCKETOS_DRIVER_TIER_BME688
#define POCKETOS_DRIVER_TIER_BME688 POCKETOS_DRIVER_TIER
#endif

// MS8607 Driver Tier (Environmental multi-sensor)
#ifndef POCKETOS_DRIVER_TIER_MS8607
#define POCKETOS_DRIVER_TIER_MS8607 POCKETOS_DRIVER_TIER
#endif

// SCD30 Driver Tier (CO2/Temp/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SCD30
#define POCKETOS_DRIVER_TIER_SCD30 POCKETOS_DRIVER_TIER
#endif

// SCD40 Driver Tier (CO2/Temp/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SCD40
#define POCKETOS_DRIVER_TIER_SCD40 POCKETOS_DRIVER_TIER
#endif

// SCD41 Driver Tier (CO2/Temp/Humidity sensor)
#ifndef POCKETOS_DRIVER_TIER_SCD41
#define POCKETOS_DRIVER_TIER_SCD41 POCKETOS_DRIVER_TIER
#endif

// BNO055 Driver Tier (9-DoF IMU with sensor fusion)
#ifndef POCKETOS_DRIVER_TIER_BNO055
#define POCKETOS_DRIVER_TIER_BNO055 POCKETOS_DRIVER_TIER
#endif

// ICM20948 Driver Tier (9-DoF IMU)
#ifndef POCKETOS_DRIVER_TIER_ICM20948
#define POCKETOS_DRIVER_TIER_ICM20948 POCKETOS_DRIVER_TIER
#endif

// FXAS21002C Driver Tier (Gyroscope)
#ifndef POCKETOS_DRIVER_TIER_FXAS21002C
#define POCKETOS_DRIVER_TIER_FXAS21002C POCKETOS_DRIVER_TIER
#endif

// FXOS8700CQ Driver Tier (Accelerometer + Magnetometer)
#ifndef POCKETOS_DRIVER_TIER_FXOS8700CQ
#define POCKETOS_DRIVER_TIER_FXOS8700CQ POCKETOS_DRIVER_TIER
#endif

// LIS2DH12 Driver Tier (3-axis Accelerometer)
#ifndef POCKETOS_DRIVER_TIER_LIS2DH12
#define POCKETOS_DRIVER_TIER_LIS2DH12 POCKETOS_DRIVER_TIER
#endif

// LIS3MDL Driver Tier (3-axis Magnetometer)
#ifndef POCKETOS_DRIVER_TIER_LIS3MDL
#define POCKETOS_DRIVER_TIER_LIS3MDL POCKETOS_DRIVER_TIER
#endif

// LSM303AGR Driver Tier (Accelerometer + Magnetometer)
#ifndef POCKETOS_DRIVER_TIER_LSM303AGR
#define POCKETOS_DRIVER_TIER_LSM303AGR POCKETOS_DRIVER_TIER
#endif

// LSM6DS33 Driver Tier (6-axis IMU)
#ifndef POCKETOS_DRIVER_TIER_LSM6DS33
#define POCKETOS_DRIVER_TIER_LSM6DS33 POCKETOS_DRIVER_TIER
#endif

// LSM6DSOX Driver Tier (6-axis IMU with ML core)
#ifndef POCKETOS_DRIVER_TIER_LSM6DSOX
#define POCKETOS_DRIVER_TIER_LSM6DSOX POCKETOS_DRIVER_TIER
#endif

// LSM9DS1 Driver Tier (9-DoF dual-chip IMU)
#ifndef POCKETOS_DRIVER_TIER_LSM9DS1
#define POCKETOS_DRIVER_TIER_LSM9DS1 POCKETOS_DRIVER_TIER
#endif

// BH1750 Driver Tier (Ambient light sensor)
#ifndef POCKETOS_DRIVER_TIER_BH1750
#define POCKETOS_DRIVER_TIER_BH1750 POCKETOS_DRIVER_TIER
#endif

// TCS34725 Driver Tier (RGB color sensor)
#ifndef POCKETOS_DRIVER_TIER_TCS34725
#define POCKETOS_DRIVER_TIER_TCS34725 POCKETOS_DRIVER_TIER
#endif

// TSL2561 Driver Tier (Lux sensor)
#ifndef POCKETOS_DRIVER_TIER_TSL2561
#define POCKETOS_DRIVER_TIER_TSL2561 POCKETOS_DRIVER_TIER
#endif

// TSL2591 Driver Tier (Lux sensor)
#ifndef POCKETOS_DRIVER_TIER_TSL2591
#define POCKETOS_DRIVER_TIER_TSL2591 POCKETOS_DRIVER_TIER
#endif

// VEML6070 Driver Tier (UV sensor)
#ifndef POCKETOS_DRIVER_TIER_VEML6070
#define POCKETOS_DRIVER_TIER_VEML6070 POCKETOS_DRIVER_TIER
#endif

// VEML6075 Driver Tier (UVA/UVB sensor)
#ifndef POCKETOS_DRIVER_TIER_VEML6075
#define POCKETOS_DRIVER_TIER_VEML6075 POCKETOS_DRIVER_TIER
#endif

// VEML7700 Driver Tier (Ambient light sensor)
#ifndef POCKETOS_DRIVER_TIER_VEML7700
#define POCKETOS_DRIVER_TIER_VEML7700 POCKETOS_DRIVER_TIER
#endif

// SI1145 Driver Tier (UV/IR/Visible sensor)
#ifndef POCKETOS_DRIVER_TIER_SI1145
#define POCKETOS_DRIVER_TIER_SI1145 POCKETOS_DRIVER_TIER
#endif

// VCNL4010 Driver Tier (Proximity/Light sensor)
#ifndef POCKETOS_DRIVER_TIER_VCNL4010
#define POCKETOS_DRIVER_TIER_VCNL4010 POCKETOS_DRIVER_TIER
#endif

// VCNL4040 Driver Tier (Proximity/Light sensor)
#ifndef POCKETOS_DRIVER_TIER_VCNL4040
#define POCKETOS_DRIVER_TIER_VCNL4040 POCKETOS_DRIVER_TIER
#endif

// MCP23008 Driver Tier (8-bit GPIO expander)
#ifndef POCKETOS_DRIVER_TIER_MCP23008
#define POCKETOS_DRIVER_TIER_MCP23008 POCKETOS_DRIVER_TIER
#endif

// MCP23017 Driver Tier (16-bit GPIO expander)
#ifndef POCKETOS_DRIVER_TIER_MCP23017
#define POCKETOS_DRIVER_TIER_MCP23017 POCKETOS_DRIVER_TIER
#endif

// PCA9536 Driver Tier (4-bit I/O expander)
#ifndef POCKETOS_DRIVER_TIER_PCA9536
#define POCKETOS_DRIVER_TIER_PCA9536 POCKETOS_DRIVER_TIER
#endif

// PCA9555 Driver Tier (16-bit I/O expander)
#ifndef POCKETOS_DRIVER_TIER_PCA9555
#define POCKETOS_DRIVER_TIER_PCA9555 POCKETOS_DRIVER_TIER
#endif

// PCAL6416A Driver Tier (16-bit GPIO expander with advanced features)
#ifndef POCKETOS_DRIVER_TIER_PCAL6416A
#define POCKETOS_DRIVER_TIER_PCAL6416A POCKETOS_DRIVER_TIER
#endif

// PCF8574 Driver Tier (8-bit quasi-bidirectional I/O)
#ifndef POCKETOS_DRIVER_TIER_PCF8574
#define POCKETOS_DRIVER_TIER_PCF8574 POCKETOS_DRIVER_TIER
#endif

// PCF8575 Driver Tier (16-bit quasi-bidirectional I/O)
#ifndef POCKETOS_DRIVER_TIER_PCF8575
#define POCKETOS_DRIVER_TIER_PCF8575 POCKETOS_DRIVER_TIER
#endif

// AW9523 Driver Tier (16-channel GPIO + LED driver)
#ifndef POCKETOS_DRIVER_TIER_AW9523
#define POCKETOS_DRIVER_TIER_AW9523 POCKETOS_DRIVER_TIER
#endif

// Add more driver tier overrides as drivers are created
// #ifndef POCKETOS_DRIVER_TIER_<DRIVER_NAME>
// #define POCKETOS_DRIVER_TIER_<DRIVER_NAME> POCKETOS_DRIVER_TIER
// #endif

// ============================================================================
// FEATURE FLAGS BASED ON TIERS
// ============================================================================

/**
 * These macros make it easy to conditionally compile features based on tier.
 * Usage in driver code:
 * 
 * #if POCKETOS_BME280_ENABLE_REGISTER_ACCESS
 *     // Tier 2 only code
 * #endif
 */

// BME280 Feature Flags
// Tier 0: Basic read functionality
#if POCKETOS_DRIVER_TIER_BME280 >= POCKETOS_TIER_0
#define POCKETOS_BME280_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BME280_ENABLE_BASIC_READ 0
#endif

// Tier 1: Robust features (calibration, configuration, extra outputs)
#if POCKETOS_DRIVER_TIER_BME280 >= POCKETOS_TIER_1
#define POCKETOS_BME280_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BME280_ENABLE_LOGGING 1
#define POCKETOS_BME280_ENABLE_CONFIGURATION 1
#define POCKETOS_BME280_ENABLE_FULL_SCHEMA 1
#define POCKETOS_BME280_ENABLE_ADVANCED_DIAGNOSTICS 1
#define POCKETOS_BME280_ENABLE_FORCED_MODE 1
#define POCKETOS_BME280_ENABLE_IIR_FILTER 1
#define POCKETOS_BME280_ENABLE_STANDBY_CONFIG 1
#define POCKETOS_BME280_ENABLE_OVERSAMPLING_CONFIG 1
#else
#define POCKETOS_BME280_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BME280_ENABLE_LOGGING 0
#define POCKETOS_BME280_ENABLE_CONFIGURATION 0
#define POCKETOS_BME280_ENABLE_FULL_SCHEMA 0
#define POCKETOS_BME280_ENABLE_ADVANCED_DIAGNOSTICS 0
#define POCKETOS_BME280_ENABLE_FORCED_MODE 0
#define POCKETOS_BME280_ENABLE_IIR_FILTER 0
#define POCKETOS_BME280_ENABLE_STANDBY_CONFIG 0
#define POCKETOS_BME280_ENABLE_OVERSAMPLING_CONFIG 0
#endif

// Tier 2: Complete + exhaustive register access
#if POCKETOS_DRIVER_TIER_BME280 >= POCKETOS_TIER_2
#define POCKETOS_BME280_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BME280_ENABLE_REGISTER_ACCESS 0
#endif

// GPIO DOUT Feature Flags
#if POCKETOS_DRIVER_TIER_GPIO_DOUT >= POCKETOS_TIER_0
#define POCKETOS_GPIO_DOUT_ENABLE_BASIC 1
#else
#define POCKETOS_GPIO_DOUT_ENABLE_BASIC 0
#endif

#if POCKETOS_DRIVER_TIER_GPIO_DOUT >= POCKETOS_TIER_1
#define POCKETOS_GPIO_DOUT_ENABLE_ERROR_HANDLING 1
#define POCKETOS_GPIO_DOUT_ENABLE_LOGGING 1
#define POCKETOS_GPIO_DOUT_ENABLE_PWM 1
#define POCKETOS_GPIO_DOUT_ENABLE_BLINK 1
#else
#define POCKETOS_GPIO_DOUT_ENABLE_ERROR_HANDLING 0
#define POCKETOS_GPIO_DOUT_ENABLE_LOGGING 0
#define POCKETOS_GPIO_DOUT_ENABLE_PWM 0
#define POCKETOS_GPIO_DOUT_ENABLE_BLINK 0
#endif

// SHT31 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SHT31 >= POCKETOS_TIER_0
#define POCKETOS_SHT31_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SHT31_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SHT31 >= POCKETOS_TIER_1
#define POCKETOS_SHT31_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SHT31_ENABLE_LOGGING 1
#define POCKETOS_SHT31_ENABLE_CONFIGURATION 1
#define POCKETOS_SHT31_ENABLE_HEATER 1
#else
#define POCKETOS_SHT31_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SHT31_ENABLE_LOGGING 0
#define POCKETOS_SHT31_ENABLE_CONFIGURATION 0
#define POCKETOS_SHT31_ENABLE_HEATER 0
#endif

// AS6212 Feature Flags (Temperature sensor)
#if POCKETOS_DRIVER_TIER_AS6212 >= POCKETOS_TIER_0
#define POCKETOS_AS6212_ENABLE_BASIC_READ 1
#else
#define POCKETOS_AS6212_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_AS6212 >= POCKETOS_TIER_1
#define POCKETOS_AS6212_ENABLE_ERROR_HANDLING 1
#define POCKETOS_AS6212_ENABLE_LOGGING 1
#define POCKETOS_AS6212_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_AS6212_ENABLE_ERROR_HANDLING 0
#define POCKETOS_AS6212_ENABLE_LOGGING 0
#define POCKETOS_AS6212_ENABLE_CONFIGURATION 0
#endif

// MCP9808 Feature Flags (Temperature sensor)
#if POCKETOS_DRIVER_TIER_MCP9808 >= POCKETOS_TIER_0
#define POCKETOS_MCP9808_ENABLE_BASIC_READ 1
#else
#define POCKETOS_MCP9808_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_MCP9808 >= POCKETOS_TIER_1
#define POCKETOS_MCP9808_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MCP9808_ENABLE_LOGGING 1
#define POCKETOS_MCP9808_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MCP9808_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MCP9808_ENABLE_LOGGING 0
#define POCKETOS_MCP9808_ENABLE_CONFIGURATION 0
#endif

// TMP102 Feature Flags (Temperature sensor)
#if POCKETOS_DRIVER_TIER_TMP102 >= POCKETOS_TIER_0
#define POCKETOS_TMP102_ENABLE_BASIC_READ 1
#else
#define POCKETOS_TMP102_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_TMP102 >= POCKETOS_TIER_1
#define POCKETOS_TMP102_ENABLE_ERROR_HANDLING 1
#define POCKETOS_TMP102_ENABLE_LOGGING 1
#define POCKETOS_TMP102_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_TMP102_ENABLE_ERROR_HANDLING 0
#define POCKETOS_TMP102_ENABLE_LOGGING 0
#define POCKETOS_TMP102_ENABLE_CONFIGURATION 0
#endif

// TMP117 Feature Flags (Temperature sensor)
#if POCKETOS_DRIVER_TIER_TMP117 >= POCKETOS_TIER_0
#define POCKETOS_TMP117_ENABLE_BASIC_READ 1
#else
#define POCKETOS_TMP117_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_TMP117 >= POCKETOS_TIER_1
#define POCKETOS_TMP117_ENABLE_ERROR_HANDLING 1
#define POCKETOS_TMP117_ENABLE_LOGGING 1
#define POCKETOS_TMP117_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_TMP117_ENABLE_ERROR_HANDLING 0
#define POCKETOS_TMP117_ENABLE_LOGGING 0
#define POCKETOS_TMP117_ENABLE_CONFIGURATION 0
#endif

// STTS751 Feature Flags (Temperature sensor)
#if POCKETOS_DRIVER_TIER_STTS751 >= POCKETOS_TIER_0
#define POCKETOS_STTS751_ENABLE_BASIC_READ 1
#else
#define POCKETOS_STTS751_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_STTS751 >= POCKETOS_TIER_1
#define POCKETOS_STTS751_ENABLE_ERROR_HANDLING 1
#define POCKETOS_STTS751_ENABLE_LOGGING 1
#define POCKETOS_STTS751_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_STTS751_ENABLE_ERROR_HANDLING 0
#define POCKETOS_STTS751_ENABLE_LOGGING 0
#define POCKETOS_STTS751_ENABLE_CONFIGURATION 0
#endif

// MLX90614 Feature Flags (Infrared temperature sensor)
#if POCKETOS_DRIVER_TIER_MLX90614 >= POCKETOS_TIER_0
#define POCKETOS_MLX90614_ENABLE_BASIC_READ 1
#else
#define POCKETOS_MLX90614_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_MLX90614 >= POCKETOS_TIER_1
#define POCKETOS_MLX90614_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MLX90614_ENABLE_LOGGING 1
#define POCKETOS_MLX90614_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MLX90614_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MLX90614_ENABLE_LOGGING 0
#define POCKETOS_MLX90614_ENABLE_CONFIGURATION 0
#endif

// AHT10 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_AHT10 >= POCKETOS_TIER_0
#define POCKETOS_AHT10_ENABLE_BASIC_READ 1
#else
#define POCKETOS_AHT10_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_AHT10 >= POCKETOS_TIER_1
#define POCKETOS_AHT10_ENABLE_ERROR_HANDLING 1
#define POCKETOS_AHT10_ENABLE_LOGGING 1
#define POCKETOS_AHT10_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_AHT10_ENABLE_ERROR_HANDLING 0
#define POCKETOS_AHT10_ENABLE_LOGGING 0
#define POCKETOS_AHT10_ENABLE_CONFIGURATION 0
#endif

// AHT20 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_AHT20 >= POCKETOS_TIER_0
#define POCKETOS_AHT20_ENABLE_BASIC_READ 1
#else
#define POCKETOS_AHT20_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_AHT20 >= POCKETOS_TIER_1
#define POCKETOS_AHT20_ENABLE_ERROR_HANDLING 1
#define POCKETOS_AHT20_ENABLE_LOGGING 1
#define POCKETOS_AHT20_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_AHT20_ENABLE_ERROR_HANDLING 0
#define POCKETOS_AHT20_ENABLE_LOGGING 0
#define POCKETOS_AHT20_ENABLE_CONFIGURATION 0
#endif

// AM2315 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_AM2315 >= POCKETOS_TIER_0
#define POCKETOS_AM2315_ENABLE_BASIC_READ 1
#else
#define POCKETOS_AM2315_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_AM2315 >= POCKETOS_TIER_1
#define POCKETOS_AM2315_ENABLE_ERROR_HANDLING 1
#define POCKETOS_AM2315_ENABLE_LOGGING 1
#define POCKETOS_AM2315_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_AM2315_ENABLE_ERROR_HANDLING 0
#define POCKETOS_AM2315_ENABLE_LOGGING 0
#define POCKETOS_AM2315_ENABLE_CONFIGURATION 0
#endif

// SI7021 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SI7021 >= POCKETOS_TIER_0
#define POCKETOS_SI7021_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SI7021_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SI7021 >= POCKETOS_TIER_1
#define POCKETOS_SI7021_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SI7021_ENABLE_LOGGING 1
#define POCKETOS_SI7021_ENABLE_CONFIGURATION 1
#define POCKETOS_SI7021_ENABLE_HEATER 1
#else
#define POCKETOS_SI7021_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SI7021_ENABLE_LOGGING 0
#define POCKETOS_SI7021_ENABLE_CONFIGURATION 0
#define POCKETOS_SI7021_ENABLE_HEATER 0
#endif

// SHT35 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SHT35 >= POCKETOS_TIER_0
#define POCKETOS_SHT35_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SHT35_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SHT35 >= POCKETOS_TIER_1
#define POCKETOS_SHT35_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SHT35_ENABLE_LOGGING 1
#define POCKETOS_SHT35_ENABLE_CONFIGURATION 1
#define POCKETOS_SHT35_ENABLE_HEATER 1
#else
#define POCKETOS_SHT35_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SHT35_ENABLE_LOGGING 0
#define POCKETOS_SHT35_ENABLE_CONFIGURATION 0
#define POCKETOS_SHT35_ENABLE_HEATER 0
#endif

// SHT40 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SHT40 >= POCKETOS_TIER_0
#define POCKETOS_SHT40_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SHT40_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SHT40 >= POCKETOS_TIER_1
#define POCKETOS_SHT40_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SHT40_ENABLE_LOGGING 1
#define POCKETOS_SHT40_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SHT40_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SHT40_ENABLE_LOGGING 0
#define POCKETOS_SHT40_ENABLE_CONFIGURATION 0
#endif

// SHT45 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SHT45 >= POCKETOS_TIER_0
#define POCKETOS_SHT45_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SHT45_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SHT45 >= POCKETOS_TIER_1
#define POCKETOS_SHT45_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SHT45_ENABLE_LOGGING 1
#define POCKETOS_SHT45_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SHT45_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SHT45_ENABLE_LOGGING 0
#define POCKETOS_SHT45_ENABLE_CONFIGURATION 0
#endif

// SHTC3 Feature Flags (Temperature/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SHTC3 >= POCKETOS_TIER_0
#define POCKETOS_SHTC3_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SHTC3_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SHTC3 >= POCKETOS_TIER_1
#define POCKETOS_SHTC3_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SHTC3_ENABLE_LOGGING 1
#define POCKETOS_SHTC3_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SHTC3_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SHTC3_ENABLE_LOGGING 0
#define POCKETOS_SHTC3_ENABLE_CONFIGURATION 0
#endif

// BMP085 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_BMP085 >= POCKETOS_TIER_0
#define POCKETOS_BMP085_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BMP085_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BMP085 >= POCKETOS_TIER_1
#define POCKETOS_BMP085_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BMP085_ENABLE_LOGGING 1
#define POCKETOS_BMP085_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BMP085_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BMP085_ENABLE_LOGGING 0
#define POCKETOS_BMP085_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BMP085 >= POCKETOS_TIER_2
#define POCKETOS_BMP085_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BMP085_ENABLE_REGISTER_ACCESS 0
#endif

// BMP180 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_BMP180 >= POCKETOS_TIER_0
#define POCKETOS_BMP180_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BMP180_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BMP180 >= POCKETOS_TIER_1
#define POCKETOS_BMP180_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BMP180_ENABLE_LOGGING 1
#define POCKETOS_BMP180_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BMP180_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BMP180_ENABLE_LOGGING 0
#define POCKETOS_BMP180_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BMP180 >= POCKETOS_TIER_2
#define POCKETOS_BMP180_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BMP180_ENABLE_REGISTER_ACCESS 0
#endif

// BMP280 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_BMP280 >= POCKETOS_TIER_0
#define POCKETOS_BMP280_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BMP280_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BMP280 >= POCKETOS_TIER_1
#define POCKETOS_BMP280_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BMP280_ENABLE_LOGGING 1
#define POCKETOS_BMP280_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BMP280_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BMP280_ENABLE_LOGGING 0
#define POCKETOS_BMP280_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BMP280 >= POCKETOS_TIER_2
#define POCKETOS_BMP280_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BMP280_ENABLE_REGISTER_ACCESS 0
#endif

// BMP388 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_BMP388 >= POCKETOS_TIER_0
#define POCKETOS_BMP388_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BMP388_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BMP388 >= POCKETOS_TIER_1
#define POCKETOS_BMP388_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BMP388_ENABLE_LOGGING 1
#define POCKETOS_BMP388_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BMP388_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BMP388_ENABLE_LOGGING 0
#define POCKETOS_BMP388_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BMP388 >= POCKETOS_TIER_2
#define POCKETOS_BMP388_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BMP388_ENABLE_REGISTER_ACCESS 0
#endif

// DPS310 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_DPS310 >= POCKETOS_TIER_0
#define POCKETOS_DPS310_ENABLE_BASIC_READ 1
#else
#define POCKETOS_DPS310_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_DPS310 >= POCKETOS_TIER_1
#define POCKETOS_DPS310_ENABLE_ERROR_HANDLING 1
#define POCKETOS_DPS310_ENABLE_LOGGING 1
#define POCKETOS_DPS310_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_DPS310_ENABLE_ERROR_HANDLING 0
#define POCKETOS_DPS310_ENABLE_LOGGING 0
#define POCKETOS_DPS310_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_DPS310 >= POCKETOS_TIER_2
#define POCKETOS_DPS310_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_DPS310_ENABLE_REGISTER_ACCESS 0
#endif

// MS5611 Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_MS5611 >= POCKETOS_TIER_0
#define POCKETOS_MS5611_ENABLE_BASIC_READ 1
#else
#define POCKETOS_MS5611_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_MS5611 >= POCKETOS_TIER_1
#define POCKETOS_MS5611_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MS5611_ENABLE_LOGGING 1
#define POCKETOS_MS5611_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MS5611_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MS5611_ENABLE_LOGGING 0
#define POCKETOS_MS5611_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_MS5611 >= POCKETOS_TIER_2
#define POCKETOS_MS5611_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_MS5611_ENABLE_REGISTER_ACCESS 0
#endif

// LPS22HB Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_LPS22HB >= POCKETOS_TIER_0
#define POCKETOS_LPS22HB_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LPS22HB_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LPS22HB >= POCKETOS_TIER_1
#define POCKETOS_LPS22HB_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LPS22HB_ENABLE_LOGGING 1
#define POCKETOS_LPS22HB_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LPS22HB_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LPS22HB_ENABLE_LOGGING 0
#define POCKETOS_LPS22HB_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LPS22HB >= POCKETOS_TIER_2
#define POCKETOS_LPS22HB_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LPS22HB_ENABLE_REGISTER_ACCESS 0
#endif

// LPS25H Feature Flags (Pressure sensor)
#if POCKETOS_DRIVER_TIER_LPS25H >= POCKETOS_TIER_0
#define POCKETOS_LPS25H_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LPS25H_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LPS25H >= POCKETOS_TIER_1
#define POCKETOS_LPS25H_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LPS25H_ENABLE_LOGGING 1
#define POCKETOS_LPS25H_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LPS25H_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LPS25H_ENABLE_LOGGING 0
#define POCKETOS_LPS25H_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LPS25H >= POCKETOS_TIER_2
#define POCKETOS_LPS25H_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LPS25H_ENABLE_REGISTER_ACCESS 0
#endif

// BME680 Feature Flags (Environmental multi-sensor)
#if POCKETOS_DRIVER_TIER_BME680 >= POCKETOS_TIER_0
#define POCKETOS_BME680_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BME680_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BME680 >= POCKETOS_TIER_1
#define POCKETOS_BME680_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BME680_ENABLE_LOGGING 1
#define POCKETOS_BME680_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BME680_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BME680_ENABLE_LOGGING 0
#define POCKETOS_BME680_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BME680 >= POCKETOS_TIER_2
#define POCKETOS_BME680_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BME680_ENABLE_REGISTER_ACCESS 0
#endif

// BME688 Feature Flags (Environmental multi-sensor)
#if POCKETOS_DRIVER_TIER_BME688 >= POCKETOS_TIER_0
#define POCKETOS_BME688_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BME688_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BME688 >= POCKETOS_TIER_1
#define POCKETOS_BME688_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BME688_ENABLE_LOGGING 1
#define POCKETOS_BME688_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BME688_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BME688_ENABLE_LOGGING 0
#define POCKETOS_BME688_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BME688 >= POCKETOS_TIER_2
#define POCKETOS_BME688_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BME688_ENABLE_REGISTER_ACCESS 0
#endif

// MS8607 Feature Flags (Environmental multi-sensor)
#if POCKETOS_DRIVER_TIER_MS8607 >= POCKETOS_TIER_0
#define POCKETOS_MS8607_ENABLE_BASIC_READ 1
#else
#define POCKETOS_MS8607_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_MS8607 >= POCKETOS_TIER_1
#define POCKETOS_MS8607_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MS8607_ENABLE_LOGGING 1
#define POCKETOS_MS8607_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MS8607_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MS8607_ENABLE_LOGGING 0
#define POCKETOS_MS8607_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_MS8607 >= POCKETOS_TIER_2
#define POCKETOS_MS8607_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_MS8607_ENABLE_REGISTER_ACCESS 0
#endif

// SCD30 Feature Flags (CO2/Temp/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SCD30 >= POCKETOS_TIER_0
#define POCKETOS_SCD30_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SCD30_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SCD30 >= POCKETOS_TIER_1
#define POCKETOS_SCD30_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SCD30_ENABLE_LOGGING 1
#define POCKETOS_SCD30_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SCD30_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SCD30_ENABLE_LOGGING 0
#define POCKETOS_SCD30_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_SCD30 >= POCKETOS_TIER_2
#define POCKETOS_SCD30_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_SCD30_ENABLE_REGISTER_ACCESS 0
#endif

// SCD40 Feature Flags (CO2/Temp/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SCD40 >= POCKETOS_TIER_0
#define POCKETOS_SCD40_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SCD40_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SCD40 >= POCKETOS_TIER_1
#define POCKETOS_SCD40_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SCD40_ENABLE_LOGGING 1
#define POCKETOS_SCD40_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SCD40_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SCD40_ENABLE_LOGGING 0
#define POCKETOS_SCD40_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_SCD40 >= POCKETOS_TIER_2
#define POCKETOS_SCD40_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_SCD40_ENABLE_REGISTER_ACCESS 0
#endif

// SCD41 Feature Flags (CO2/Temp/Humidity sensor)
#if POCKETOS_DRIVER_TIER_SCD41 >= POCKETOS_TIER_0
#define POCKETOS_SCD41_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SCD41_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SCD41 >= POCKETOS_TIER_1
#define POCKETOS_SCD41_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SCD41_ENABLE_LOGGING 1
#define POCKETOS_SCD41_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SCD41_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SCD41_ENABLE_LOGGING 0
#define POCKETOS_SCD41_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_SCD41 >= POCKETOS_TIER_2
#define POCKETOS_SCD41_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_SCD41_ENABLE_REGISTER_ACCESS 0
#endif

// BNO055 Feature Flags (9-DoF IMU with sensor fusion)
#if POCKETOS_DRIVER_TIER_BNO055 >= POCKETOS_TIER_0
#define POCKETOS_BNO055_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BNO055_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BNO055 >= POCKETOS_TIER_1
#define POCKETOS_BNO055_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BNO055_ENABLE_LOGGING 1
#define POCKETOS_BNO055_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BNO055_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BNO055_ENABLE_LOGGING 0
#define POCKETOS_BNO055_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BNO055 >= POCKETOS_TIER_2
#define POCKETOS_BNO055_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BNO055_ENABLE_REGISTER_ACCESS 0
#endif

// ICM20948 Feature Flags (9-DoF IMU)
#if POCKETOS_DRIVER_TIER_ICM20948 >= POCKETOS_TIER_0
#define POCKETOS_ICM20948_ENABLE_BASIC_READ 1
#else
#define POCKETOS_ICM20948_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_ICM20948 >= POCKETOS_TIER_1
#define POCKETOS_ICM20948_ENABLE_ERROR_HANDLING 1
#define POCKETOS_ICM20948_ENABLE_LOGGING 1
#define POCKETOS_ICM20948_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_ICM20948_ENABLE_ERROR_HANDLING 0
#define POCKETOS_ICM20948_ENABLE_LOGGING 0
#define POCKETOS_ICM20948_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_ICM20948 >= POCKETOS_TIER_2
#define POCKETOS_ICM20948_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_ICM20948_ENABLE_REGISTER_ACCESS 0
#endif

// FXAS21002C Feature Flags (Gyroscope)
#if POCKETOS_DRIVER_TIER_FXAS21002C >= POCKETOS_TIER_0
#define POCKETOS_FXAS21002C_ENABLE_BASIC_READ 1
#else
#define POCKETOS_FXAS21002C_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_FXAS21002C >= POCKETOS_TIER_1
#define POCKETOS_FXAS21002C_ENABLE_ERROR_HANDLING 1
#define POCKETOS_FXAS21002C_ENABLE_LOGGING 1
#define POCKETOS_FXAS21002C_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_FXAS21002C_ENABLE_ERROR_HANDLING 0
#define POCKETOS_FXAS21002C_ENABLE_LOGGING 0
#define POCKETOS_FXAS21002C_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_FXAS21002C >= POCKETOS_TIER_2
#define POCKETOS_FXAS21002C_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_FXAS21002C_ENABLE_REGISTER_ACCESS 0
#endif

// FXOS8700CQ Feature Flags (Accelerometer + Magnetometer)
#if POCKETOS_DRIVER_TIER_FXOS8700CQ >= POCKETOS_TIER_0
#define POCKETOS_FXOS8700CQ_ENABLE_BASIC_READ 1
#else
#define POCKETOS_FXOS8700CQ_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_FXOS8700CQ >= POCKETOS_TIER_1
#define POCKETOS_FXOS8700CQ_ENABLE_ERROR_HANDLING 1
#define POCKETOS_FXOS8700CQ_ENABLE_LOGGING 1
#define POCKETOS_FXOS8700CQ_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_FXOS8700CQ_ENABLE_ERROR_HANDLING 0
#define POCKETOS_FXOS8700CQ_ENABLE_LOGGING 0
#define POCKETOS_FXOS8700CQ_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_FXOS8700CQ >= POCKETOS_TIER_2
#define POCKETOS_FXOS8700CQ_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_FXOS8700CQ_ENABLE_REGISTER_ACCESS 0
#endif

// LIS2DH12 Feature Flags (3-axis Accelerometer)
#if POCKETOS_DRIVER_TIER_LIS2DH12 >= POCKETOS_TIER_0
#define POCKETOS_LIS2DH12_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LIS2DH12_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LIS2DH12 >= POCKETOS_TIER_1
#define POCKETOS_LIS2DH12_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LIS2DH12_ENABLE_LOGGING 1
#define POCKETOS_LIS2DH12_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LIS2DH12_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LIS2DH12_ENABLE_LOGGING 0
#define POCKETOS_LIS2DH12_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LIS2DH12 >= POCKETOS_TIER_2
#define POCKETOS_LIS2DH12_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LIS2DH12_ENABLE_REGISTER_ACCESS 0
#endif

// LIS3MDL Feature Flags (3-axis Magnetometer)
#if POCKETOS_DRIVER_TIER_LIS3MDL >= POCKETOS_TIER_0
#define POCKETOS_LIS3MDL_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LIS3MDL_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LIS3MDL >= POCKETOS_TIER_1
#define POCKETOS_LIS3MDL_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LIS3MDL_ENABLE_LOGGING 1
#define POCKETOS_LIS3MDL_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LIS3MDL_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LIS3MDL_ENABLE_LOGGING 0
#define POCKETOS_LIS3MDL_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LIS3MDL >= POCKETOS_TIER_2
#define POCKETOS_LIS3MDL_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LIS3MDL_ENABLE_REGISTER_ACCESS 0
#endif

// LSM303AGR Feature Flags (Accelerometer + Magnetometer)
#if POCKETOS_DRIVER_TIER_LSM303AGR >= POCKETOS_TIER_0
#define POCKETOS_LSM303AGR_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LSM303AGR_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LSM303AGR >= POCKETOS_TIER_1
#define POCKETOS_LSM303AGR_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LSM303AGR_ENABLE_LOGGING 1
#define POCKETOS_LSM303AGR_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LSM303AGR_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LSM303AGR_ENABLE_LOGGING 0
#define POCKETOS_LSM303AGR_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LSM303AGR >= POCKETOS_TIER_2
#define POCKETOS_LSM303AGR_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LSM303AGR_ENABLE_REGISTER_ACCESS 0
#endif

// LSM6DS33 Feature Flags (6-axis IMU)
#if POCKETOS_DRIVER_TIER_LSM6DS33 >= POCKETOS_TIER_0
#define POCKETOS_LSM6DS33_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LSM6DS33_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LSM6DS33 >= POCKETOS_TIER_1
#define POCKETOS_LSM6DS33_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LSM6DS33_ENABLE_LOGGING 1
#define POCKETOS_LSM6DS33_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LSM6DS33_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LSM6DS33_ENABLE_LOGGING 0
#define POCKETOS_LSM6DS33_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LSM6DS33 >= POCKETOS_TIER_2
#define POCKETOS_LSM6DS33_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LSM6DS33_ENABLE_REGISTER_ACCESS 0
#endif

// LSM6DSOX Feature Flags (6-axis IMU with ML core)
#if POCKETOS_DRIVER_TIER_LSM6DSOX >= POCKETOS_TIER_0
#define POCKETOS_LSM6DSOX_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LSM6DSOX_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LSM6DSOX >= POCKETOS_TIER_1
#define POCKETOS_LSM6DSOX_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LSM6DSOX_ENABLE_LOGGING 1
#define POCKETOS_LSM6DSOX_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LSM6DSOX_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LSM6DSOX_ENABLE_LOGGING 0
#define POCKETOS_LSM6DSOX_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LSM6DSOX >= POCKETOS_TIER_2
#define POCKETOS_LSM6DSOX_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LSM6DSOX_ENABLE_REGISTER_ACCESS 0
#endif

// LSM9DS1 Feature Flags (9-DoF dual-chip IMU)
#if POCKETOS_DRIVER_TIER_LSM9DS1 >= POCKETOS_TIER_0
#define POCKETOS_LSM9DS1_ENABLE_BASIC_READ 1
#else
#define POCKETOS_LSM9DS1_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_LSM9DS1 >= POCKETOS_TIER_1
#define POCKETOS_LSM9DS1_ENABLE_ERROR_HANDLING 1
#define POCKETOS_LSM9DS1_ENABLE_LOGGING 1
#define POCKETOS_LSM9DS1_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_LSM9DS1_ENABLE_ERROR_HANDLING 0
#define POCKETOS_LSM9DS1_ENABLE_LOGGING 0
#define POCKETOS_LSM9DS1_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_LSM9DS1 >= POCKETOS_TIER_2
#define POCKETOS_LSM9DS1_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_LSM9DS1_ENABLE_REGISTER_ACCESS 0
#endif

// BH1750 Feature Flags (Ambient light sensor)
#if POCKETOS_DRIVER_TIER_BH1750 >= POCKETOS_TIER_0
#define POCKETOS_BH1750_ENABLE_BASIC_READ 1
#else
#define POCKETOS_BH1750_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_BH1750 >= POCKETOS_TIER_1
#define POCKETOS_BH1750_ENABLE_ERROR_HANDLING 1
#define POCKETOS_BH1750_ENABLE_LOGGING 1
#define POCKETOS_BH1750_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_BH1750_ENABLE_ERROR_HANDLING 0
#define POCKETOS_BH1750_ENABLE_LOGGING 0
#define POCKETOS_BH1750_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_BH1750 >= POCKETOS_TIER_2
#define POCKETOS_BH1750_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_BH1750_ENABLE_REGISTER_ACCESS 0
#endif

// TCS34725 Feature Flags (RGB color sensor)
#if POCKETOS_DRIVER_TIER_TCS34725 >= POCKETOS_TIER_0
#define POCKETOS_TCS34725_ENABLE_BASIC_READ 1
#else
#define POCKETOS_TCS34725_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_TCS34725 >= POCKETOS_TIER_1
#define POCKETOS_TCS34725_ENABLE_ERROR_HANDLING 1
#define POCKETOS_TCS34725_ENABLE_LOGGING 1
#define POCKETOS_TCS34725_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_TCS34725_ENABLE_ERROR_HANDLING 0
#define POCKETOS_TCS34725_ENABLE_LOGGING 0
#define POCKETOS_TCS34725_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_TCS34725 >= POCKETOS_TIER_2
#define POCKETOS_TCS34725_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_TCS34725_ENABLE_REGISTER_ACCESS 0
#endif

// TSL2561 Feature Flags (Lux sensor)
#if POCKETOS_DRIVER_TIER_TSL2561 >= POCKETOS_TIER_0
#define POCKETOS_TSL2561_ENABLE_BASIC_READ 1
#else
#define POCKETOS_TSL2561_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_TSL2561 >= POCKETOS_TIER_1
#define POCKETOS_TSL2561_ENABLE_ERROR_HANDLING 1
#define POCKETOS_TSL2561_ENABLE_LOGGING 1
#define POCKETOS_TSL2561_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_TSL2561_ENABLE_ERROR_HANDLING 0
#define POCKETOS_TSL2561_ENABLE_LOGGING 0
#define POCKETOS_TSL2561_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_TSL2561 >= POCKETOS_TIER_2
#define POCKETOS_TSL2561_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_TSL2561_ENABLE_REGISTER_ACCESS 0
#endif

// TSL2591 Feature Flags (Lux sensor)
#if POCKETOS_DRIVER_TIER_TSL2591 >= POCKETOS_TIER_0
#define POCKETOS_TSL2591_ENABLE_BASIC_READ 1
#else
#define POCKETOS_TSL2591_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_TSL2591 >= POCKETOS_TIER_1
#define POCKETOS_TSL2591_ENABLE_ERROR_HANDLING 1
#define POCKETOS_TSL2591_ENABLE_LOGGING 1
#define POCKETOS_TSL2591_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_TSL2591_ENABLE_ERROR_HANDLING 0
#define POCKETOS_TSL2591_ENABLE_LOGGING 0
#define POCKETOS_TSL2591_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_TSL2591 >= POCKETOS_TIER_2
#define POCKETOS_TSL2591_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_TSL2591_ENABLE_REGISTER_ACCESS 0
#endif

// VEML6070 Feature Flags (UV sensor)
#if POCKETOS_DRIVER_TIER_VEML6070 >= POCKETOS_TIER_0
#define POCKETOS_VEML6070_ENABLE_BASIC_READ 1
#else
#define POCKETOS_VEML6070_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_VEML6070 >= POCKETOS_TIER_1
#define POCKETOS_VEML6070_ENABLE_ERROR_HANDLING 1
#define POCKETOS_VEML6070_ENABLE_LOGGING 1
#define POCKETOS_VEML6070_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_VEML6070_ENABLE_ERROR_HANDLING 0
#define POCKETOS_VEML6070_ENABLE_LOGGING 0
#define POCKETOS_VEML6070_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_VEML6070 >= POCKETOS_TIER_2
#define POCKETOS_VEML6070_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_VEML6070_ENABLE_REGISTER_ACCESS 0
#endif

// VEML6075 Feature Flags (UVA/UVB sensor)
#if POCKETOS_DRIVER_TIER_VEML6075 >= POCKETOS_TIER_0
#define POCKETOS_VEML6075_ENABLE_BASIC_READ 1
#else
#define POCKETOS_VEML6075_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_VEML6075 >= POCKETOS_TIER_1
#define POCKETOS_VEML6075_ENABLE_ERROR_HANDLING 1
#define POCKETOS_VEML6075_ENABLE_LOGGING 1
#define POCKETOS_VEML6075_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_VEML6075_ENABLE_ERROR_HANDLING 0
#define POCKETOS_VEML6075_ENABLE_LOGGING 0
#define POCKETOS_VEML6075_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_VEML6075 >= POCKETOS_TIER_2
#define POCKETOS_VEML6075_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_VEML6075_ENABLE_REGISTER_ACCESS 0
#endif

// VEML7700 Feature Flags (Ambient light sensor)
#if POCKETOS_DRIVER_TIER_VEML7700 >= POCKETOS_TIER_0
#define POCKETOS_VEML7700_ENABLE_BASIC_READ 1
#else
#define POCKETOS_VEML7700_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_VEML7700 >= POCKETOS_TIER_1
#define POCKETOS_VEML7700_ENABLE_ERROR_HANDLING 1
#define POCKETOS_VEML7700_ENABLE_LOGGING 1
#define POCKETOS_VEML7700_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_VEML7700_ENABLE_ERROR_HANDLING 0
#define POCKETOS_VEML7700_ENABLE_LOGGING 0
#define POCKETOS_VEML7700_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_VEML7700 >= POCKETOS_TIER_2
#define POCKETOS_VEML7700_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_VEML7700_ENABLE_REGISTER_ACCESS 0
#endif

// SI1145 Feature Flags (UV/IR/Visible sensor)
#if POCKETOS_DRIVER_TIER_SI1145 >= POCKETOS_TIER_0
#define POCKETOS_SI1145_ENABLE_BASIC_READ 1
#else
#define POCKETOS_SI1145_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_SI1145 >= POCKETOS_TIER_1
#define POCKETOS_SI1145_ENABLE_ERROR_HANDLING 1
#define POCKETOS_SI1145_ENABLE_LOGGING 1
#define POCKETOS_SI1145_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_SI1145_ENABLE_ERROR_HANDLING 0
#define POCKETOS_SI1145_ENABLE_LOGGING 0
#define POCKETOS_SI1145_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_SI1145 >= POCKETOS_TIER_2
#define POCKETOS_SI1145_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_SI1145_ENABLE_REGISTER_ACCESS 0
#endif

// VCNL4010 Feature Flags (Proximity/Light sensor)
#if POCKETOS_DRIVER_TIER_VCNL4010 >= POCKETOS_TIER_0
#define POCKETOS_VCNL4010_ENABLE_BASIC_READ 1
#else
#define POCKETOS_VCNL4010_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_VCNL4010 >= POCKETOS_TIER_1
#define POCKETOS_VCNL4010_ENABLE_ERROR_HANDLING 1
#define POCKETOS_VCNL4010_ENABLE_LOGGING 1
#define POCKETOS_VCNL4010_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_VCNL4010_ENABLE_ERROR_HANDLING 0
#define POCKETOS_VCNL4010_ENABLE_LOGGING 0
#define POCKETOS_VCNL4010_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_VCNL4010 >= POCKETOS_TIER_2
#define POCKETOS_VCNL4010_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_VCNL4010_ENABLE_REGISTER_ACCESS 0
#endif

// VCNL4040 Feature Flags (Proximity/Light sensor)
#if POCKETOS_DRIVER_TIER_VCNL4040 >= POCKETOS_TIER_0
#define POCKETOS_VCNL4040_ENABLE_BASIC_READ 1
#else
#define POCKETOS_VCNL4040_ENABLE_BASIC_READ 0
#endif

#if POCKETOS_DRIVER_TIER_VCNL4040 >= POCKETOS_TIER_1
#define POCKETOS_VCNL4040_ENABLE_ERROR_HANDLING 1
#define POCKETOS_VCNL4040_ENABLE_LOGGING 1
#define POCKETOS_VCNL4040_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_VCNL4040_ENABLE_ERROR_HANDLING 0
#define POCKETOS_VCNL4040_ENABLE_LOGGING 0
#define POCKETOS_VCNL4040_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_VCNL4040 >= POCKETOS_TIER_2
#define POCKETOS_VCNL4040_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_VCNL4040_ENABLE_REGISTER_ACCESS 0
#endif

// MCP23008 Feature Flags (8-bit GPIO expander)
#if POCKETOS_DRIVER_TIER_MCP23008 >= POCKETOS_TIER_0
#define POCKETOS_MCP23008_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_MCP23008_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_MCP23008 >= POCKETOS_TIER_1
#define POCKETOS_MCP23008_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MCP23008_ENABLE_LOGGING 1
#define POCKETOS_MCP23008_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MCP23008_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MCP23008_ENABLE_LOGGING 0
#define POCKETOS_MCP23008_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_MCP23008 >= POCKETOS_TIER_2
#define POCKETOS_MCP23008_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_MCP23008_ENABLE_REGISTER_ACCESS 0
#endif

// MCP23017 Feature Flags (16-bit GPIO expander)
#if POCKETOS_DRIVER_TIER_MCP23017 >= POCKETOS_TIER_0
#define POCKETOS_MCP23017_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_MCP23017_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_MCP23017 >= POCKETOS_TIER_1
#define POCKETOS_MCP23017_ENABLE_ERROR_HANDLING 1
#define POCKETOS_MCP23017_ENABLE_LOGGING 1
#define POCKETOS_MCP23017_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_MCP23017_ENABLE_ERROR_HANDLING 0
#define POCKETOS_MCP23017_ENABLE_LOGGING 0
#define POCKETOS_MCP23017_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_MCP23017 >= POCKETOS_TIER_2
#define POCKETOS_MCP23017_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_MCP23017_ENABLE_REGISTER_ACCESS 0
#endif

// PCA9536 Feature Flags (4-bit I/O expander)
#if POCKETOS_DRIVER_TIER_PCA9536 >= POCKETOS_TIER_0
#define POCKETOS_PCA9536_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_PCA9536_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_PCA9536 >= POCKETOS_TIER_1
#define POCKETOS_PCA9536_ENABLE_ERROR_HANDLING 1
#define POCKETOS_PCA9536_ENABLE_LOGGING 1
#define POCKETOS_PCA9536_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_PCA9536_ENABLE_ERROR_HANDLING 0
#define POCKETOS_PCA9536_ENABLE_LOGGING 0
#define POCKETOS_PCA9536_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_PCA9536 >= POCKETOS_TIER_2
#define POCKETOS_PCA9536_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_PCA9536_ENABLE_REGISTER_ACCESS 0
#endif

// PCA9555 Feature Flags (16-bit I/O expander)
#if POCKETOS_DRIVER_TIER_PCA9555 >= POCKETOS_TIER_0
#define POCKETOS_PCA9555_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_PCA9555_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_PCA9555 >= POCKETOS_TIER_1
#define POCKETOS_PCA9555_ENABLE_ERROR_HANDLING 1
#define POCKETOS_PCA9555_ENABLE_LOGGING 1
#define POCKETOS_PCA9555_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_PCA9555_ENABLE_ERROR_HANDLING 0
#define POCKETOS_PCA9555_ENABLE_LOGGING 0
#define POCKETOS_PCA9555_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_PCA9555 >= POCKETOS_TIER_2
#define POCKETOS_PCA9555_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_PCA9555_ENABLE_REGISTER_ACCESS 0
#endif

// PCAL6416A Feature Flags (16-bit GPIO expander with advanced features)
#if POCKETOS_DRIVER_TIER_PCAL6416A >= POCKETOS_TIER_0
#define POCKETOS_PCAL6416A_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_PCAL6416A_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_PCAL6416A >= POCKETOS_TIER_1
#define POCKETOS_PCAL6416A_ENABLE_ERROR_HANDLING 1
#define POCKETOS_PCAL6416A_ENABLE_LOGGING 1
#define POCKETOS_PCAL6416A_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_PCAL6416A_ENABLE_ERROR_HANDLING 0
#define POCKETOS_PCAL6416A_ENABLE_LOGGING 0
#define POCKETOS_PCAL6416A_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_PCAL6416A >= POCKETOS_TIER_2
#define POCKETOS_PCAL6416A_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_PCAL6416A_ENABLE_REGISTER_ACCESS 0
#endif

// PCF8574 Feature Flags (8-bit quasi-bidirectional I/O)
#if POCKETOS_DRIVER_TIER_PCF8574 >= POCKETOS_TIER_0
#define POCKETOS_PCF8574_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_PCF8574_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_PCF8574 >= POCKETOS_TIER_1
#define POCKETOS_PCF8574_ENABLE_ERROR_HANDLING 1
#define POCKETOS_PCF8574_ENABLE_LOGGING 1
#define POCKETOS_PCF8574_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_PCF8574_ENABLE_ERROR_HANDLING 0
#define POCKETOS_PCF8574_ENABLE_LOGGING 0
#define POCKETOS_PCF8574_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_PCF8574 >= POCKETOS_TIER_2
#define POCKETOS_PCF8574_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_PCF8574_ENABLE_REGISTER_ACCESS 0
#endif

// PCF8575 Feature Flags (16-bit quasi-bidirectional I/O)
#if POCKETOS_DRIVER_TIER_PCF8575 >= POCKETOS_TIER_0
#define POCKETOS_PCF8575_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_PCF8575_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_PCF8575 >= POCKETOS_TIER_1
#define POCKETOS_PCF8575_ENABLE_ERROR_HANDLING 1
#define POCKETOS_PCF8575_ENABLE_LOGGING 1
#define POCKETOS_PCF8575_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_PCF8575_ENABLE_ERROR_HANDLING 0
#define POCKETOS_PCF8575_ENABLE_LOGGING 0
#define POCKETOS_PCF8575_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_PCF8575 >= POCKETOS_TIER_2
#define POCKETOS_PCF8575_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_PCF8575_ENABLE_REGISTER_ACCESS 0
#endif

// AW9523 Feature Flags (16-channel GPIO + LED driver)
#if POCKETOS_DRIVER_TIER_AW9523 >= POCKETOS_TIER_0
#define POCKETOS_AW9523_ENABLE_BASIC_GPIO 1
#else
#define POCKETOS_AW9523_ENABLE_BASIC_GPIO 0
#endif

#if POCKETOS_DRIVER_TIER_AW9523 >= POCKETOS_TIER_1
#define POCKETOS_AW9523_ENABLE_ERROR_HANDLING 1
#define POCKETOS_AW9523_ENABLE_LOGGING 1
#define POCKETOS_AW9523_ENABLE_CONFIGURATION 1
#else
#define POCKETOS_AW9523_ENABLE_ERROR_HANDLING 0
#define POCKETOS_AW9523_ENABLE_LOGGING 0
#define POCKETOS_AW9523_ENABLE_CONFIGURATION 0
#endif

#if POCKETOS_DRIVER_TIER_AW9523 >= POCKETOS_TIER_2
#define POCKETOS_AW9523_ENABLE_REGISTER_ACCESS 1
#else
#define POCKETOS_AW9523_ENABLE_REGISTER_ACCESS 0
#endif

// ============================================================================
// TIER INFORMATION MACROS
// ============================================================================

// Helper macros to get tier name as string
#define POCKETOS_TIER_NAME(tier) \
    ((tier) == POCKETOS_TIER_0 ? "TIER_0" : \
     (tier) == POCKETOS_TIER_1 ? "TIER_1" : \
     (tier) == POCKETOS_TIER_2 ? "TIER_2" : "UNKNOWN")

// Get current global tier name
#define POCKETOS_GLOBAL_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER)

// Get specific driver tier name
#define POCKETOS_BME280_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BME280)
#define POCKETOS_GPIO_DOUT_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_GPIO_DOUT)
#define POCKETOS_SHT31_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SHT31)
#define POCKETOS_AS6212_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_AS6212)
#define POCKETOS_MCP9808_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MCP9808)
#define POCKETOS_TMP102_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_TMP102)
#define POCKETOS_TMP117_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_TMP117)
#define POCKETOS_STTS751_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_STTS751)
#define POCKETOS_MLX90614_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MLX90614)
#define POCKETOS_AHT10_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_AHT10)
#define POCKETOS_AHT20_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_AHT20)
#define POCKETOS_AM2315_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_AM2315)
#define POCKETOS_SI7021_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SI7021)
#define POCKETOS_SHT35_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SHT35)
#define POCKETOS_SHT40_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SHT40)
#define POCKETOS_SHT45_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SHT45)
#define POCKETOS_SHTC3_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SHTC3)
#define POCKETOS_BMP085_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BMP085)
#define POCKETOS_BMP180_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BMP180)
#define POCKETOS_BMP280_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BMP280)
#define POCKETOS_BMP388_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BMP388)
#define POCKETOS_DPS310_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_DPS310)
#define POCKETOS_MS5611_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MS5611)
#define POCKETOS_LPS22HB_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LPS22HB)
#define POCKETOS_LPS25H_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LPS25H)
#define POCKETOS_BME680_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BME680)
#define POCKETOS_BME688_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BME688)
#define POCKETOS_MS8607_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MS8607)
#define POCKETOS_SCD30_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SCD30)
#define POCKETOS_SCD40_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SCD40)
#define POCKETOS_SCD41_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SCD41)
#define POCKETOS_BNO055_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BNO055)
#define POCKETOS_ICM20948_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_ICM20948)
#define POCKETOS_FXAS21002C_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_FXAS21002C)
#define POCKETOS_FXOS8700CQ_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_FXOS8700CQ)
#define POCKETOS_LIS2DH12_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LIS2DH12)
#define POCKETOS_LIS3MDL_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LIS3MDL)
#define POCKETOS_LSM303AGR_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LSM303AGR)
#define POCKETOS_LSM6DS33_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LSM6DS33)
#define POCKETOS_LSM6DSOX_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LSM6DSOX)
#define POCKETOS_LSM9DS1_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_LSM9DS1)
#define POCKETOS_BH1750_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_BH1750)
#define POCKETOS_TCS34725_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_TCS34725)
#define POCKETOS_TSL2561_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_TSL2561)
#define POCKETOS_TSL2591_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_TSL2591)
#define POCKETOS_VEML6070_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_VEML6070)
#define POCKETOS_VEML6075_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_VEML6075)
#define POCKETOS_VEML7700_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_VEML7700)
#define POCKETOS_SI1145_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_SI1145)
#define POCKETOS_VCNL4010_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_VCNL4010)
#define POCKETOS_VCNL4040_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_VCNL4040)
#define POCKETOS_MCP23008_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MCP23008)
#define POCKETOS_MCP23017_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_MCP23017)
#define POCKETOS_PCA9536_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_PCA9536)
#define POCKETOS_PCA9555_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_PCA9555)
#define POCKETOS_PCAL6416A_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_PCAL6416A)
#define POCKETOS_PCF8574_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_PCF8574)
#define POCKETOS_PCF8575_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_PCF8575)
#define POCKETOS_AW9523_TIER_NAME POCKETOS_TIER_NAME(POCKETOS_DRIVER_TIER_AW9523)

// ============================================================================
// VALIDATION
// ============================================================================

// Validate tier values are in range
#if POCKETOS_DRIVER_TIER < 0 || POCKETOS_DRIVER_TIER > 2
#error "POCKETOS_DRIVER_TIER must be 0 (TIER_0), 1 (TIER_1), or 2 (TIER_2)"
#endif

#if POCKETOS_DRIVER_TIER_BME280 < 0 || POCKETOS_DRIVER_TIER_BME280 > 2
#error "POCKETOS_DRIVER_TIER_BME280 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_GPIO_DOUT < 0 || POCKETOS_DRIVER_TIER_GPIO_DOUT > 2
#error "POCKETOS_DRIVER_TIER_GPIO_DOUT must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SHT31 < 0 || POCKETOS_DRIVER_TIER_SHT31 > 2
#error "POCKETOS_DRIVER_TIER_SHT31 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_AS6212 < 0 || POCKETOS_DRIVER_TIER_AS6212 > 2
#error "POCKETOS_DRIVER_TIER_AS6212 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MCP9808 < 0 || POCKETOS_DRIVER_TIER_MCP9808 > 2
#error "POCKETOS_DRIVER_TIER_MCP9808 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_TMP102 < 0 || POCKETOS_DRIVER_TIER_TMP102 > 2
#error "POCKETOS_DRIVER_TIER_TMP102 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_TMP117 < 0 || POCKETOS_DRIVER_TIER_TMP117 > 2
#error "POCKETOS_DRIVER_TIER_TMP117 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_STTS751 < 0 || POCKETOS_DRIVER_TIER_STTS751 > 2
#error "POCKETOS_DRIVER_TIER_STTS751 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MLX90614 < 0 || POCKETOS_DRIVER_TIER_MLX90614 > 2
#error "POCKETOS_DRIVER_TIER_MLX90614 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_AHT10 < 0 || POCKETOS_DRIVER_TIER_AHT10 > 2
#error "POCKETOS_DRIVER_TIER_AHT10 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_AHT20 < 0 || POCKETOS_DRIVER_TIER_AHT20 > 2
#error "POCKETOS_DRIVER_TIER_AHT20 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_AM2315 < 0 || POCKETOS_DRIVER_TIER_AM2315 > 2
#error "POCKETOS_DRIVER_TIER_AM2315 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SI7021 < 0 || POCKETOS_DRIVER_TIER_SI7021 > 2
#error "POCKETOS_DRIVER_TIER_SI7021 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SHT35 < 0 || POCKETOS_DRIVER_TIER_SHT35 > 2
#error "POCKETOS_DRIVER_TIER_SHT35 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SHT40 < 0 || POCKETOS_DRIVER_TIER_SHT40 > 2
#error "POCKETOS_DRIVER_TIER_SHT40 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SHT45 < 0 || POCKETOS_DRIVER_TIER_SHT45 > 2
#error "POCKETOS_DRIVER_TIER_SHT45 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SHTC3 < 0 || POCKETOS_DRIVER_TIER_SHTC3 > 2
#error "POCKETOS_DRIVER_TIER_SHTC3 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BMP085 < 0 || POCKETOS_DRIVER_TIER_BMP085 > 2
#error "POCKETOS_DRIVER_TIER_BMP085 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BMP180 < 0 || POCKETOS_DRIVER_TIER_BMP180 > 2
#error "POCKETOS_DRIVER_TIER_BMP180 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BMP280 < 0 || POCKETOS_DRIVER_TIER_BMP280 > 2
#error "POCKETOS_DRIVER_TIER_BMP280 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BMP388 < 0 || POCKETOS_DRIVER_TIER_BMP388 > 2
#error "POCKETOS_DRIVER_TIER_BMP388 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_DPS310 < 0 || POCKETOS_DRIVER_TIER_DPS310 > 2
#error "POCKETOS_DRIVER_TIER_DPS310 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MS5611 < 0 || POCKETOS_DRIVER_TIER_MS5611 > 2
#error "POCKETOS_DRIVER_TIER_MS5611 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_LPS22HB < 0 || POCKETOS_DRIVER_TIER_LPS22HB > 2
#error "POCKETOS_DRIVER_TIER_LPS22HB must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_LPS25H < 0 || POCKETOS_DRIVER_TIER_LPS25H > 2
#error "POCKETOS_DRIVER_TIER_LPS25H must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BME680 < 0 || POCKETOS_DRIVER_TIER_BME680 > 2
#error "POCKETOS_DRIVER_TIER_BME680 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BME688 < 0 || POCKETOS_DRIVER_TIER_BME688 > 2
#error "POCKETOS_DRIVER_TIER_BME688 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MS8607 < 0 || POCKETOS_DRIVER_TIER_MS8607 > 2
#error "POCKETOS_DRIVER_TIER_MS8607 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SCD30 < 0 || POCKETOS_DRIVER_TIER_SCD30 > 2
#error "POCKETOS_DRIVER_TIER_SCD30 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SCD40 < 0 || POCKETOS_DRIVER_TIER_SCD40 > 2
#error "POCKETOS_DRIVER_TIER_SCD40 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SCD41 < 0 || POCKETOS_DRIVER_TIER_SCD41 > 2
#error "POCKETOS_DRIVER_TIER_SCD41 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_BH1750 < 0 || POCKETOS_DRIVER_TIER_BH1750 > 2
#error "POCKETOS_DRIVER_TIER_BH1750 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_TCS34725 < 0 || POCKETOS_DRIVER_TIER_TCS34725 > 2
#error "POCKETOS_DRIVER_TIER_TCS34725 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_TSL2561 < 0 || POCKETOS_DRIVER_TIER_TSL2561 > 2
#error "POCKETOS_DRIVER_TIER_TSL2561 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_TSL2591 < 0 || POCKETOS_DRIVER_TIER_TSL2591 > 2
#error "POCKETOS_DRIVER_TIER_TSL2591 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_VEML6070 < 0 || POCKETOS_DRIVER_TIER_VEML6070 > 2
#error "POCKETOS_DRIVER_TIER_VEML6070 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_VEML6075 < 0 || POCKETOS_DRIVER_TIER_VEML6075 > 2
#error "POCKETOS_DRIVER_TIER_VEML6075 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_VEML7700 < 0 || POCKETOS_DRIVER_TIER_VEML7700 > 2
#error "POCKETOS_DRIVER_TIER_VEML7700 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_SI1145 < 0 || POCKETOS_DRIVER_TIER_SI1145 > 2
#error "POCKETOS_DRIVER_TIER_SI1145 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_VCNL4010 < 0 || POCKETOS_DRIVER_TIER_VCNL4010 > 2
#error "POCKETOS_DRIVER_TIER_VCNL4010 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_VCNL4040 < 0 || POCKETOS_DRIVER_TIER_VCNL4040 > 2
#error "POCKETOS_DRIVER_TIER_VCNL4040 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MCP23008 < 0 || POCKETOS_DRIVER_TIER_MCP23008 > 2
#error "POCKETOS_DRIVER_TIER_MCP23008 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_MCP23017 < 0 || POCKETOS_DRIVER_TIER_MCP23017 > 2
#error "POCKETOS_DRIVER_TIER_MCP23017 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_PCA9536 < 0 || POCKETOS_DRIVER_TIER_PCA9536 > 2
#error "POCKETOS_DRIVER_TIER_PCA9536 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_PCA9555 < 0 || POCKETOS_DRIVER_TIER_PCA9555 > 2
#error "POCKETOS_DRIVER_TIER_PCA9555 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_PCAL6416A < 0 || POCKETOS_DRIVER_TIER_PCAL6416A > 2
#error "POCKETOS_DRIVER_TIER_PCAL6416A must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_PCF8574 < 0 || POCKETOS_DRIVER_TIER_PCF8574 > 2
#error "POCKETOS_DRIVER_TIER_PCF8574 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_PCF8575 < 0 || POCKETOS_DRIVER_TIER_PCF8575 > 2
#error "POCKETOS_DRIVER_TIER_PCF8575 must be 0, 1, or 2"
#endif

#if POCKETOS_DRIVER_TIER_AW9523 < 0 || POCKETOS_DRIVER_TIER_AW9523 > 2
#error "POCKETOS_DRIVER_TIER_AW9523 must be 0, 1, or 2"
#endif

#endif // POCKETOS_DRIVER_CONFIG_H
